/*

 CARDTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 21

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define CardTilesBank 0

/* Super Gameboy palette 0 */
#define CardTilesSGBPal0c0 6076
#define CardTilesSGBPal0c1 8935
#define CardTilesSGBPal0c2 6596
#define CardTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define CardTilesSGBPal1c0 6076
#define CardTilesSGBPal1c1 8935
#define CardTilesSGBPal1c2 6596
#define CardTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define CardTilesSGBPal2c0 6076
#define CardTilesSGBPal2c1 8935
#define CardTilesSGBPal2c2 6596
#define CardTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define CardTilesSGBPal3c0 6076
#define CardTilesSGBPal3c1 8935
#define CardTilesSGBPal3c2 6596
#define CardTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define CardTilesCGBPal0c0 32767
#define CardTilesCGBPal0c1 25368
#define CardTilesCGBPal0c2 223
#define CardTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define CardTilesCGBPal1c0 6076
#define CardTilesCGBPal1c1 8935
#define CardTilesCGBPal1c2 6596
#define CardTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define CardTilesCGBPal2c0 6076
#define CardTilesCGBPal2c1 8935
#define CardTilesCGBPal2c2 6596
#define CardTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define CardTilesCGBPal3c0 6076
#define CardTilesCGBPal3c1 8935
#define CardTilesCGBPal3c2 6596
#define CardTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define CardTilesCGBPal4c0 6076
#define CardTilesCGBPal4c1 8935
#define CardTilesCGBPal4c2 6596
#define CardTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define CardTilesCGBPal5c0 6076
#define CardTilesCGBPal5c1 8935
#define CardTilesCGBPal5c2 6596
#define CardTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define CardTilesCGBPal6c0 6076
#define CardTilesCGBPal6c1 8935
#define CardTilesCGBPal6c2 6596
#define CardTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define CardTilesCGBPal7c0 6076
#define CardTilesCGBPal7c1 8935
#define CardTilesCGBPal7c2 6596
#define CardTilesCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char CardTilesCGB[];
/* Start of tile array. */
extern unsigned char CardTiles[];

/* End of CARDTILES.H */
