/*

 NEOBJTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 74

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define neoBjCardsBank 0

/* Super Gameboy palette 0 */
#define neoBjCardsSGBPal0c0 6076
#define neoBjCardsSGBPal0c1 8935
#define neoBjCardsSGBPal0c2 6596
#define neoBjCardsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define neoBjCardsSGBPal1c0 6076
#define neoBjCardsSGBPal1c1 8935
#define neoBjCardsSGBPal1c2 6596
#define neoBjCardsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define neoBjCardsSGBPal2c0 6076
#define neoBjCardsSGBPal2c1 8935
#define neoBjCardsSGBPal2c2 6596
#define neoBjCardsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define neoBjCardsSGBPal3c0 6076
#define neoBjCardsSGBPal3c1 8935
#define neoBjCardsSGBPal3c2 6596
#define neoBjCardsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define neoBjCardsCGBPal0c0 32767
#define neoBjCardsCGBPal0c1 31935
#define neoBjCardsCGBPal0c2 7138
#define neoBjCardsCGBPal0c3 0

/* Gameboy Color palette 1 */
#define neoBjCardsCGBPal1c0 32767
#define neoBjCardsCGBPal1c1 26425
#define neoBjCardsCGBPal1c2 7138
#define neoBjCardsCGBPal1c3 0

/* Gameboy Color palette 2 */
#define neoBjCardsCGBPal2c0 32767
#define neoBjCardsCGBPal2c1 32448
#define neoBjCardsCGBPal2c2 23040
#define neoBjCardsCGBPal2c3 0

/* Gameboy Color palette 3 */
#define neoBjCardsCGBPal3c0 6076
#define neoBjCardsCGBPal3c1 8935
#define neoBjCardsCGBPal3c2 6596
#define neoBjCardsCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define neoBjCardsCGBPal4c0 6076
#define neoBjCardsCGBPal4c1 8935
#define neoBjCardsCGBPal4c2 6596
#define neoBjCardsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define neoBjCardsCGBPal5c0 6076
#define neoBjCardsCGBPal5c1 8935
#define neoBjCardsCGBPal5c2 6596
#define neoBjCardsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define neoBjCardsCGBPal6c0 6076
#define neoBjCardsCGBPal6c1 8935
#define neoBjCardsCGBPal6c2 6596
#define neoBjCardsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define neoBjCardsCGBPal7c0 6076
#define neoBjCardsCGBPal7c1 8935
#define neoBjCardsCGBPal7c2 6596
#define neoBjCardsCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char neoBjCardsCGB[];
/* Start of tile array. */
extern unsigned char neoBjCards[];

/* End of NEOBJTILES.H */
