/*

 NEOBJMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\jt578\Desktop\GB\gbr project\BJ\ass\NeoBj.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define neoBjMapWidth 20
#define neoBjMapHeight 18
#define neoBjMapBank 0

#define neoBjMap neoBjMapPLN0
extern unsigned char neoBjMapPLN0[];
extern unsigned char neoBjMapPLN1[];

/* End of NEOBJMAP.H */
