/*

 COINTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 5

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define coinBank 0

/* Super Gameboy palette 0 */
#define coinSGBPal0c0 6076
#define coinSGBPal0c1 8935
#define coinSGBPal0c2 6596
#define coinSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define coinSGBPal1c0 6076
#define coinSGBPal1c1 8935
#define coinSGBPal1c2 6596
#define coinSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define coinSGBPal2c0 6076
#define coinSGBPal2c1 8935
#define coinSGBPal2c2 6596
#define coinSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define coinSGBPal3c0 6076
#define coinSGBPal3c1 8935
#define coinSGBPal3c2 6596
#define coinSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define coinCGBPal0c0 32767
#define coinCGBPal0c1 1023
#define coinCGBPal0c2 860
#define coinCGBPal0c3 0

/* Gameboy Color palette 1 */
#define coinCGBPal1c0 6076
#define coinCGBPal1c1 8935
#define coinCGBPal1c2 6596
#define coinCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define coinCGBPal2c0 6076
#define coinCGBPal2c1 8935
#define coinCGBPal2c2 6596
#define coinCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define coinCGBPal3c0 6076
#define coinCGBPal3c1 8935
#define coinCGBPal3c2 6596
#define coinCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define coinCGBPal4c0 6076
#define coinCGBPal4c1 8935
#define coinCGBPal4c2 6596
#define coinCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define coinCGBPal5c0 6076
#define coinCGBPal5c1 8935
#define coinCGBPal5c2 6596
#define coinCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define coinCGBPal6c0 6076
#define coinCGBPal6c1 8935
#define coinCGBPal6c2 6596
#define coinCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define coinCGBPal7c0 6076
#define coinCGBPal7c1 8935
#define coinCGBPal7c2 6596
#define coinCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char coinCGB[];
/* Start of tile array. */
extern unsigned char coin[];

/* End of COINTILES.H */
