/*

 TRASHBARREL.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TrashBarrelBank 0

/* Super Gameboy palette 0 */
#define TrashBarrelSGBPal0c0 6076
#define TrashBarrelSGBPal0c1 8935
#define TrashBarrelSGBPal0c2 6596
#define TrashBarrelSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define TrashBarrelSGBPal1c0 6076
#define TrashBarrelSGBPal1c1 8935
#define TrashBarrelSGBPal1c2 6596
#define TrashBarrelSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TrashBarrelSGBPal2c0 6076
#define TrashBarrelSGBPal2c1 8935
#define TrashBarrelSGBPal2c2 6596
#define TrashBarrelSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TrashBarrelSGBPal3c0 6076
#define TrashBarrelSGBPal3c1 8935
#define TrashBarrelSGBPal3c2 6596
#define TrashBarrelSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TrashBarrelCGBPal0c0 32767
#define TrashBarrelCGBPal0c1 499
#define TrashBarrelCGBPal0c2 1325
#define TrashBarrelCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TrashBarrelCGBPal1c0 6076
#define TrashBarrelCGBPal1c1 8935
#define TrashBarrelCGBPal1c2 6596
#define TrashBarrelCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define TrashBarrelCGBPal2c0 6076
#define TrashBarrelCGBPal2c1 8935
#define TrashBarrelCGBPal2c2 6596
#define TrashBarrelCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TrashBarrelCGBPal3c0 6076
#define TrashBarrelCGBPal3c1 8935
#define TrashBarrelCGBPal3c2 6596
#define TrashBarrelCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TrashBarrelCGBPal4c0 6076
#define TrashBarrelCGBPal4c1 8935
#define TrashBarrelCGBPal4c2 6596
#define TrashBarrelCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TrashBarrelCGBPal5c0 6076
#define TrashBarrelCGBPal5c1 8935
#define TrashBarrelCGBPal5c2 6596
#define TrashBarrelCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TrashBarrelCGBPal6c0 6076
#define TrashBarrelCGBPal6c1 8935
#define TrashBarrelCGBPal6c2 6596
#define TrashBarrelCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TrashBarrelCGBPal7c0 6076
#define TrashBarrelCGBPal7c1 8935
#define TrashBarrelCGBPal7c2 6596
#define TrashBarrelCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char TrashBarrelCGB[];
/* Start of tile array. */
extern unsigned char TrashBarrel[];

/* End of TRASHBARREL.H */
