/*

 TRASHBARREL.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* CGBpalette entries. */
unsigned char TrashBarrelCGB[] =
{
  0x00
};
/* Start of tile array. */
unsigned char TrashBarrel[] =
{
  0x00,0x7E,0x7E,0x81,0x7E,0x81,0x81,0x7E,
  0xAA,0x55,0xAA,0x55,0xAA,0x55,0x00,0x7E
};

/* End of TRASHBARREL.C */
